### ISSUE TITLE
AWS Encryption SDK for PHP

### ISSUE THREAD

**Issue by martinssipenko** [awsdocs/aws-encryption-sdk-docs#12]
Hi,

I'm wondering if there are any plans for introducing Encryption SDK for PHP? Is there any way one could contribute to it? Perhaps someone from AWS can get in touch with me or put in touch with someone that could help here.

**Comment by juneb** [comment]
Hi, Martins! 

Thanks so much for your interest in a PHP implementation of the AWS Encryption SDK. We'd like to support customers in every language and environment, but because there are so many, we have to balance those needs against our available resources and new feature development. 

That said, the ESDK is an open-source project, and it would be great to have an Encryption SDK in PHP. However, we cannot guarantee that we will never introduce similar functionality. If you’d like to develop a PHP implementation, please keep in mind that AWS might create duplicate functionality in the future. 

We can offer the following resources:
* [AWS Encryption SDK Specification](https://github.com/awslabs/aws-encryption-sdk-specification)
This specification guides the design of the Encryption SDKs and helps us to keep them consistent and interoperable.

* This doc repo, which represents the content in the [AWS Encryption SDK Developer Guide](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html). These topics explain the high-level architecture and concepts, and help application developers to start working with the Encryption SDKs.
